homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret hass_property_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret hass_timezone
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logger:

hacs:
  token: !secret my_github_access_token

breaking_changes:

ifttt:
  key: !secret hass_ifttt_api
    
recorder:
  db_url: !secret hass_mariadb_url

# Discover some devices automatically
discovery:
  ignore:
    - yeelight
    
stream:

camera: 
  - platform: generic
    name: Dining_Room
    still_image_url: http://192.168.1.28/tmpfs/auto.jpg
    stream_source: rtsp://192.168.1.28:554/11
    verify_ssl: false
    username: !secret hass_dining_camera_user
    password: !secret hass_dining_camera_pass
    authentication: basic
  - platform: generic
    name: Hallway
    still_image_url: http://user:user111!@192.168.1.25:8081/
    stream_source: http://user:user111!@192.168.1.25:8081/
    verify_ssl: false
  - platform: generic
    name: aneliya
    still_image_url: http://192.168.1.28/tmpfs/auto.jpg
    stream_source: rtsp://192.168.1.28:554/11
    verify_ssl: false
    username: !secret hass_dining_camera_user
    password: !secret hass_dining_camera_pass
    authentication: basic

wake_on_lan:

yeelight:
  devices:
    192.168.1.96:
      name: Bedroom

zwave:
  usb_path: /dev/ttyACM0

media_player:
  - platform: spotify
    client_id: !secret hass_spotify_client_id
    client_secret: !secret hass_spotify_client_secret

spotcast:
  username: !secret hass_spotify_username
  password: !secret hass_spotify_password

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret hass_xiaomi_key
      mac: !secret hass_xiaomi_mac
      host: 192.168.1.53

evohome:
  username: !secret evohome_user
  password: !secret evohome_pass

# Text to speech
tts:
  - platform: google_translate

# Config

switch: !include config/switches.yaml
sensor: !include config/sensors.yaml
binary_sensor: !include config/binary_sensors.yaml

# Automations

automation: !include_dir_merge_list automations/
script: !include scripts.yaml

# UI

group: !include groups.yaml
